# Generated by Django 4.2.16 on 2024-12-08 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empreendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='imagen',
            name='imagen',
            field=models.ImageField(upload_to='<django.db.models.query_utils.DeferredAttribute object at 0x000002037F6607C0>-<django.db.models.query_utils.DeferredAttribute object at 0x000002037F660550>'),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='empreendimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.empreendimento'),
        ),
        migrations.DeleteModel(
            name='Empreendimeto',
        ),
    ]
