# Generated by Django 4.2.16 on 2024-12-08 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_empreendimento_alter_imagen_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empreendimento',
            name='total_disponivel',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='empreendimento',
            name='total_lotes',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='imagen',
            field=models.ImageField(upload_to='<django.db.models.query_utils.DeferredAttribute object at 0x000001BA99226BE0>-<django.db.models.query_utils.DeferredAttribute object at 0x000001BA99226940>'),
        ),
    ]
