# Generated by Django 4.2.16 on 2024-12-08 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_empreendimento_total_disponivel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='imagen',
            field=models.ImageField(upload_to='<django.db.models.query_utils.DeferredAttribute object at 0x000002434CC86BE0>-<django.db.models.query_utils.DeferredAttribute object at 0x000002434CC86940>'),
        ),
    ]
