# Generated by Django 4.2.16 on 2024-12-08 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_imagen_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='imagen',
            field=models.ImageField(upload_to='<django.db.models.query_utils.DeferredAttribute object at 0x0000019221586BE0>-<django.db.models.query_utils.DeferredAttribute object at 0x0000019221586940>'),
        ),
    ]
