# Generated by Django 4.2.16 on 2024-12-09 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_imagen_empreendimento_alter_imagen_imagen'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Imagen',
            new_name='Imagem',
        ),
        migrations.RenameField(
            model_name='imagem',
            old_name='imagen',
            new_name='imagem',
        ),
    ]
